[base]
appName = 'data-transfer'
logPath = 'C:/develop/logs/transfer'

[kafka]
addr = '127.0.0.1:9092'       # Kafka bootstrap brokers to connect to, as a comma separated list
group = 'test-consumer-group'    # Kafka consumer group definition
assignor = "range"               # Consumer group partition assignment strategy (range, roundrobin, sticky)
oldest = true                    # Kafka consumer consume initial offset from oldest
topicAction = "user_action"        # user action kafka topic

[influxdb]
addr = 'http://127.0.0.1:8086'
token = 'token'
bucket = 'testBucket'
org = 'anthonyzero'
batchSize = 5000
flushInterval = 1000